### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by host452b** [kimyoon-young/centerNet-deep-sort#20]
python demo_centernet_deepsort.py 

then i got these ~

<module 'sys' (built-in)>
Traceback (most recent call last):
  File "demo_centernet_deepsort.py", line 10, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/detectors/exdet.py", line 26, in <module>
    from .base_detector import BaseDetector
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/models/networks/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
  File "/home/joe/Desktop/centerNet-deep-sort/CenterNet/src/lib/models/networks/DCNv2/_ext/dcn_v2/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/joe/anaconda3/envs/CenterNet_test/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by Ujang24** [comment]
you can check the answer from this comment: [https://github.com/pytorch/pytorch/issues/15645](url)
The main idea is to downgrade the pytorch version into 0.4.1
What solve my problem is:
pip3 install torch==0.4.1 torchvision==0.2.1

**Comment by zldrobit** [comment]
You can upgrade CenterNet to work with Pytorch 1.0+ using 
[CenterNet works ok on Pytorch 1.1 + Cuda10.1 + Win10](https://github.com/xingyizhou/CenterNet/issues/7#issue-434735858)
